#!/usr/bin/env python3
"""Turn the spec's vectors.json into tests/vectors.hpp, so the test binary needs no JSON parser.

Usage: tools/gen_vectors.py path/to/vectors.json > tests/vectors.hpp
"""
import json
import sys


def words(ws):
    return "{" + ", ".join(f"0x{w}u" for w in ws) + "}"


def main(path):
    v = json.load(open(path))
    out = []
    out.append("/* Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit. */")
    out.append("#pragma once")
    out.append("#include <cstdint>")
    out.append(f"#define VEC_K {v['K']}u")
    out.append(f"static const uint32_t VEC_KEY[4] = {words(v['key'])};")

    out.append("static const struct { uint32_t o[4], h[4], o_out[4], h_out[4]; } VEC_T[] = {")
    for t in v["T"]:
        out.append(f"    {{{words(t['o'])}, {words(t['h'])}, {words(t['o_out'])}, {words(t['h_out'])}}},")
    out.append("};")

    out.append("static const struct { uint64_t counter; uint32_t o[4], h[4]; } VEC_F[] = {")
    for f in v["F"]:
        assert f["domain"] == "DOMAIN_STREAM" and f["aux"] == "AUX_STREAM"
        out.append(f"    {{{f['counter']}u, {words(f['o'])}, {words(f['h'])}}},")
    out.append("};")

    out.append("static const struct { uint64_t first_word; uint32_t words[4]; } VEC_STREAM[] = {")
    for s in v["stream_words"]:
        out.append(f"    {{{s['first_word']}u, {words(s['words'])}}},")
    out.append("};")

    d = v["draws_from_position_0"]
    out.append("static const struct { uint64_t index; double value; } VEC_F64[] = {")
    for k, x in d["Float64"].items():
        out.append(f"    {{{k}u, {x!r}}},")
    out.append("};")
    out.append("static const struct { uint64_t index; float value; } VEC_F32[] = {")
    for k, x in d["Float32"].items():
        out.append(f"    {{{k}u, {x!r}f}},")
    out.append("};")
    out.append("static const struct { uint64_t index; int value; } VEC_BOOL[] = {")
    for k, x in d["Bool"].items():
        out.append(f"    {{{k}u, {x}}},")
    out.append("};")

    k = v["derived_keys"]
    out.append(f"static const uint32_t VEC_SPLIT0[4] = {words(k['split_child_0'])};")
    out.append(f"static const uint32_t VEC_SPLIT1[4] = {words(k['split_child_1'])};")
    out.append(f"static const uint32_t VEC_FORK0[4] = {words(k['fork_child_0_at_block_0'])};")
    out.append(f"static const uint32_t VEC_PURPOSE7[4] = {words(k['purpose_7'])};")

    s = v["seed_whitening"]
    out.append(f"#define VEC_SEED {s['seed']}u")
    out.append(f"static const uint32_t VEC_SEED_KEY[4] = {words(s['key'])};")
    out.append("static const struct { uint64_t index; double value; } VEC_SEED_F64[] = {")
    for kk, x in s["Float64"].items():
        out.append(f"    {{{kk}u, {x!r}}},")
    out.append("};")
    out.append("static const struct { uint64_t index; uint32_t value; } VEC_SEED_U32[] = {")
    for kk, x in s["UInt32"].items():
        out.append(f"    {{{kk}u, 0x{x}u}},")
    out.append("};")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
